In [402]:

import pandas as pd
import numpy as np
import requests as r
import json as j
import ast as a
import pprint as pp

In [69]:

odds_api_key = ''

sport = 'baseball_mlb' # use the sport_key from the /sports endpoint below, or use 'upcoming' to see the next 8 games across all sports

regions = 'us' #multiple can be specified if comma delimited

markets = 'h2h,spreads'

bookmakers = 'us,us2'

odds_format = 'american'

date_format = 'iso'

all_format = 'true'
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
#
# First get a list of in-season sports
#   The sport 'key' from the response can be used to get odds in the next request
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

sports_response = r.get(
    'https://api.the-odds-api.com/v4/sports', 
    params={
        'api_key': odds_api_key,
        'regions': regions,
        'sport': sport,
        'all': all_format
    }
)


if sports_response.status_code != 200:
    print(f'Failed to get sports: status_code {sports_response.status_code}, response body {sports_response.text}')

else:
    print('List of in season sports:', sports_response.json())
    #dump the list of dictionaries provided by json output via api call in to a python data structure for further parsing
    sports_data = j.dumps(sports_response.json())
    #turn string to list
    sports_load_data = j.loads(sports_data)
    #iterate through list to get dictionaries
    df_sports = pd.DataFrame(sports_load_data)




    # Check the usage quota
    print('Remaining requests', sports_response.headers['x-requests-remaining'])
    print('Used requests', sports_response.headers['x-requests-used'])

df_sports.to_csv('list_of_sports.csv',index=True)

List of in season sports: [{'key': 'americanfootball_cfl', 'group': 'American Football', 'title': 'CFL', 'description': 'Canadian Football League', 'active': False, 'has_outrights': False}, {'key': 'americanfootball_ncaaf', 'group': 'American Football', 'title': 'NCAAF', 'description': 'US College Football', 'active': True, 'has_outrights': False}, {'key': 'americanfootball_ncaaf_championship_winner', 'group': 'American Football', 'title': 'NCAAF Championship Winner', 'description': 'US College Football Championship Winner', 'active': True, 'has_outrights': True}, {'key': 'americanfootball_nfl', 'group': 'American Football', 'title': 'NFL', 'description': 'US Football', 'active': False, 'has_outrights': False}, {'key': 'americanfootball_nfl_preseason', 'group': 'American Football', 'title': 'NFL Preseason', 'description': 'US Football', 'active': False, 'has_outrights': False}, {'key': 'americanfootball_nfl_super_bowl_winner', 'group': 'American Football', 'title': 'NFL Super Bowl Winner', 'description': 'Super Bowl Winner 2024/2025', 'active': True, 'has_outrights': True}, {'key': 'americanfootball_ufl', 'group': 'American Football', 'title': 'UFL', 'description': 'United Football League', 'active': True, 'has_outrights': False}, {'key': 'aussierules_afl', 'group': 'Aussie Rules', 'title': 'AFL', 'description': 'Aussie Football', 'active': True, 'has_outrights': False}, {'key': 'baseball_kbo', 'group': 'Baseball', 'title': 'KBO', 'description': 'KBO League', 'active': True, 'has_outrights': False}, {'key': 'baseball_mlb', 'group': 'Baseball', 'title': 'MLB', 'description': 'Major League Baseball', 'active': True, 'has_outrights': False}, {'key': 'baseball_mlb_preseason', 'group': 'Baseball', 'title': 'MLB Preseason', 'description': 'Major League Baseball', 'active': False, 'has_outrights': False}, {'key': 'baseball_mlb_world_series_winner', 'group': 'Baseball', 'title': 'MLB World Series Winner', 'description': 'World Series Winner 2024', 'active': True, 'has_outrights': True}, {'key': 'baseball_ncaa', 'group': 'Baseball', 'title': 'NCAA Baseball', 'description': 'US College Baseball', 'active': True, 'has_outrights': False}, {'key': 'baseball_npb', 'group': 'Baseball', 'title': 'NPB', 'description': 'Nippon Professional Baseball', 'active': True, 'has_outrights': False}, {'key': 'basketball_euroleague', 'group': 'Basketball', 'title': 'Basketball Euroleague', 'description': 'Basketball Euroleague', 'active': True, 'has_outrights': False}, {'key': 'basketball_nba', 'group': 'Basketball', 'title': 'NBA', 'description': 'US Basketball', 'active': True, 'has_outrights': False}, {'key': 'basketball_nba_championship_winner', 'group': 'Basketball', 'title': 'NBA Championship Winner', 'description': 'Championship Winner 2023/2024', 'active': True, 'has_outrights': True}, {'key': 'basketball_nba_preseason', 'group': 'Basketball', 'title': 'NBA Preseason', 'description': 'US Basketball', 'active': False, 'has_outrights': False}, {'key': 'basketball_ncaab', 'group': 'Basketball', 'title': 'NCAAB', 'description': 'US College Basketball', 'active': True, 'has_outrights': False}, {'key': 'basketball_ncaab_championship_winner', 'group': 'Basketball', 'title': 'NCAAB Championship Winner', 'description': 'US College Basketball Championship Winner', 'active': True, 'has_outrights': True}, {'key': 'basketball_wnba', 'group': 'Basketball', 'title': 'WNBA', 'description': 'US Basketball', 'active': False, 'has_outrights': False}, {'key': 'boxing_boxing', 'group': 'Boxing', 'title': 'Boxing', 'description': 'Boxing Bouts', 'active': True, 'has_outrights': False}, {'key': 'cricket_asia_cup', 'group': 'Cricket', 'title': 'Asia Cup', 'description': 'Asia Cup', 'active': False, 'has_outrights': False}, {'key': 'cricket_big_bash', 'group': 'Cricket', 'title': 'Big Bash', 'description': 'Big Bash League', 'active': False, 'has_outrights': False}, {'key': 'cricket_caribbean_premier_league', 'group': 'Cricket', 'title': 'CPLT20', 'description': 'Caribbean Premier League', 'active': False, 'has_outrights': False}, {'key': 'cricket_icc_world_cup', 'group': 'Cricket', 'title': 'ICC World Cup', 'description': 'ICC World Cup', 'active': False, 'has_outrights': False}, {'key': 'cricket_international_t20', 'group': 'Cricket', 'title': 'International Twenty20', 'description': 'International Twenty20', 'active': True, 'has_outrights': False}, {'key': 'cricket_ipl', 'group': 'Cricket', 'title': 'IPL', 'description': 'Indian Premier League', 'active': True, 'has_outrights': False}, {'key': 'cricket_odi', 'group': 'Cricket', 'title': 'One Day Internationals', 'description': 'One Day Internationals', 'active': False, 'has_outrights': False}, {'key': 'cricket_psl', 'group': 'Cricket', 'title': 'Pakistan Super League', 'description': 'Pakistan Super League', 'active': False, 'has_outrights': False}, {'key': 'cricket_t20_blast', 'group': 'Cricket', 'title': 'T20 Blast', 'description': 'T20 Blast', 'active': False, 'has_outrights': False}, {'key': 'cricket_test_match', 'group': 'Cricket', 'title': 'Test Matches', 'description': 'International Test Matches', 'active': False, 'has_outrights': False}, {'key': 'cricket_the_hundred', 'group': 'Cricket', 'title': 'The Hundred', 'description': 'The Hundred', 'active': False, 'has_outrights': False}, {'key': 'golf_masters_tournament_winner', 'group': 'Golf', 'title': 'Masters Tournament Winner', 'description': '2024 Winner', 'active': True, 'has_outrights': True}, {'key': 'golf_pga_championship_winner', 'group': 'Golf', 'title': 'PGA Championship Winner', 'description': '2024 Winner', 'active': True, 'has_outrights': True}, {'key': 'golf_the_open_championship_winner', 'group': 'Golf', 'title': 'The Open Winner', 'description': '2024 Winner', 'active': True, 'has_outrights': True}, {'key': 'golf_us_open_winner', 'group': 'Golf', 'title': 'US Open Winner', 'description': '2024 Winner', 'active': True, 'has_outrights': True}, {'key': 'icehockey_nhl', 'group': 'Ice Hockey', 'title': 'NHL', 'description': 'US Ice Hockey', 'active': True, 'has_outrights': False}, {'key': 'icehockey_nhl_championship_winner', 'group': 'Ice Hockey', 'title': 'NHL Championship Winner', 'description': 'Stanley Cup Winner 2023/2024', 'active': True, 'has_outrights': True}, {'key': 'icehockey_sweden_allsvenskan', 'group': 'Ice Hockey', 'title': 'HockeyAllsvenskan', 'description': 'Swedish Hockey Allsvenskan', 'active': True, 'has_outrights': False}, {'key': 'icehockey_sweden_hockey_league', 'group': 'Ice Hockey', 'title': 'SHL', 'description': 'Swedish Hockey League', 'active': True, 'has_outrights': False}, {'key': 'mma_mixed_martial_arts', 'group': 'Mixed Martial Arts', 'title': 'MMA', 'description': 'Mixed Martial Arts', 'active': True, 'has_outrights': False}, {'key': 'politics_us_presidential_election_winner', 'group': 'Politics', 'title': 'US Presidential Elections Winner', 'description': '2024 US Presidential Election Winner', 'active': True, 'has_outrights': True}, {'key': 'rugbyleague_nrl', 'group': 'Rugby League', 'title': 'NRL', 'description': 'Aussie Rugby League', 'active': True, 'has_outrights': False}, {'key': 'rugbyunion_world_cup', 'group': 'Rugby Union', 'title': 'World Cup', 'description': 'World Cup 2023', 'active': False, 'has_outrights': False}, {'key': 'soccer_africa_cup_of_nations', 'group': 'Soccer', 'title': 'Africa Cup of Nations', 'description': 'Africa Cup of Nations', 'active': False, 'has_outrights': False}, {'key': 'soccer_argentina_primera_division', 'group': 'Soccer', 'title': 'Primera División - Argentina', 'description': 'Argentine Primera División', 'active': False, 'has_outrights': False}, {'key': 'soccer_australia_aleague', 'group': 'Soccer', 'title': 'A-League', 'description': 'Aussie Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_austria_bundesliga', 'group': 'Soccer', 'title': 'Austrian Football Bundesliga', 'description': 'Austrian Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_belgium_first_div', 'group': 'Soccer', 'title': 'Belgium First Div', 'description': 'Belgian First Division A', 'active': True, 'has_outrights': False}, {'key': 'soccer_brazil_campeonato', 'group': 'Soccer', 'title': 'Brazil Série A', 'description': 'Brasileirão Série A', 'active': True, 'has_outrights': False}, {'key': 'soccer_brazil_serie_b', 'group': 'Soccer', 'title': 'Brazil Série B', 'description': 'Campeonato Brasileiro Série B', 'active': True, 'has_outrights': False}, {'key': 'soccer_chile_campeonato', 'group': 'Soccer', 'title': 'Primera División - Chile', 'description': 'Campeonato Chileno', 'active': True, 'has_outrights': False}, {'key': 'soccer_china_superleague', 'group': 'Soccer', 'title': 'Super League - China', 'description': 'Chinese Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_conmebol_copa_libertadores', 'group': 'Soccer', 'title': 'Copa Libertadores', 'description': 'CONMEBOL Copa Libertadores', 'active': True, 'has_outrights': False}, {'key': 'soccer_denmark_superliga', 'group': 'Soccer', 'title': 'Denmark Superliga', 'description': 'Danish Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_efl_champ', 'group': 'Soccer', 'title': 'Championship', 'description': 'EFL Championship', 'active': True, 'has_outrights': False}, {'key': 'soccer_england_efl_cup', 'group': 'Soccer', 'title': 'EFL Cup', 'description': 'League Cup', 'active': False, 'has_outrights': False}, {'key': 'soccer_england_league1', 'group': 'Soccer', 'title': 'League 1', 'description': 'EFL League 1', 'active': True, 'has_outrights': False}, {'key': 'soccer_england_league2', 'group': 'Soccer', 'title': 'League 2', 'description': 'EFL League 2 ', 'active': True, 'has_outrights': False}, {'key': 'soccer_epl', 'group': 'Soccer', 'title': 'EPL', 'description': 'English Premier League', 'active': True, 'has_outrights': False}, {'key': 'soccer_fa_cup', 'group': 'Soccer', 'title': 'FA Cup', 'description': 'Football Association Challenge Cup', 'active': True, 'has_outrights': False}, {'key': 'soccer_fifa_world_cup', 'group': 'Soccer', 'title': 'FIFA World Cup', 'description': 'FIFA World Cup 2022', 'active': False, 'has_outrights': False}, {'key': 'soccer_fifa_world_cup_winner', 'group': 'Soccer', 'title': 'FIFA World Cup Winner', 'description': 'FIFA World Cup Winner 2026', 'active': True, 'has_outrights': True}, {'key': 'soccer_fifa_world_cup_womens', 'group': 'Soccer', 'title': "FIFA Women's World Cup", 'description': "FIFA Women's World Cup", 'active': False, 'has_outrights': False}, {'key': 'soccer_finland_veikkausliiga', 'group': 'Soccer', 'title': 'Veikkausliiga - Finland', 'description': 'Finnish  Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_france_ligue_one', 'group': 'Soccer', 'title': 'Ligue 1 - France', 'description': 'French Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_france_ligue_two', 'group': 'Soccer', 'title': 'Ligue 2 - France', 'description': 'French Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_germany_bundesliga', 'group': 'Soccer', 'title': 'Bundesliga - Germany', 'description': 'German Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_germany_bundesliga2', 'group': 'Soccer', 'title': 'Bundesliga 2 - Germany', 'description': 'German Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_germany_liga3', 'group': 'Soccer', 'title': '3. Liga - Germany', 'description': 'German Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_greece_super_league', 'group': 'Soccer', 'title': 'Super League - Greece', 'description': 'Greek Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_italy_serie_a', 'group': 'Soccer', 'title': 'Serie A - Italy', 'description': 'Italian Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_italy_serie_b', 'group': 'Soccer', 'title': 'Serie B - Italy', 'description': 'Italian Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_japan_j_league', 'group': 'Soccer', 'title': 'J League', 'description': 'Japan Soccer League', 'active': True, 'has_outrights': False}, {'key': 'soccer_korea_kleague1', 'group': 'Soccer', 'title': 'K League 1', 'description': 'Korean Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_league_of_ireland', 'group': 'Soccer', 'title': 'League of Ireland', 'description': 'Airtricity League Premier Division', 'active': True, 'has_outrights': False}, {'key': 'soccer_mexico_ligamx', 'group': 'Soccer', 'title': 'Liga MX', 'description': 'Mexican Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_netherlands_eredivisie', 'group': 'Soccer', 'title': 'Dutch Eredivisie', 'description': 'Dutch Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_norway_eliteserien', 'group': 'Soccer', 'title': 'Eliteserien - Norway', 'description': 'Norwegian Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_poland_ekstraklasa', 'group': 'Soccer', 'title': 'Ekstraklasa - Poland', 'description': 'Polish Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_portugal_primeira_liga', 'group': 'Soccer', 'title': 'Primeira Liga - Portugal', 'description': 'Portugese Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_spain_la_liga', 'group': 'Soccer', 'title': 'La Liga - Spain', 'description': 'Spanish Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_spain_segunda_division', 'group': 'Soccer', 'title': 'La Liga 2 - Spain', 'description': 'Spanish Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_spl', 'group': 'Soccer', 'title': 'Premiership - Scotland', 'description': 'Scottish Premiership', 'active': True, 'has_outrights': False}, {'key': 'soccer_sweden_allsvenskan', 'group': 'Soccer', 'title': 'Allsvenskan - Sweden', 'description': 'Swedish Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_sweden_superettan', 'group': 'Soccer', 'title': 'Superettan - Sweden', 'description': 'Swedish Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_switzerland_superleague', 'group': 'Soccer', 'title': 'Swiss Superleague', 'description': 'Swiss Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_turkey_super_league', 'group': 'Soccer', 'title': 'Turkey Super League', 'description': 'Turkish Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_uefa_champs_league', 'group': 'Soccer', 'title': 'UEFA Champions League', 'description': 'European Champions League', 'active': True, 'has_outrights': False}, {'key': 'soccer_uefa_champs_league_qualification', 'group': 'Soccer', 'title': 'UEFA Champions League Qualification', 'description': 'European Champions League Qualification', 'active': False, 'has_outrights': False}, {'key': 'soccer_uefa_euro_qualification', 'group': 'Soccer', 'title': 'UEFA Euro Qualification', 'description': 'European Championship Qualification', 'active': False, 'has_outrights': False}, {'key': 'soccer_uefa_europa_conference_league', 'group': 'Soccer', 'title': 'UEFA Europa Conference League', 'description': 'UEFA Europa Conference League', 'active': True, 'has_outrights': False}, {'key': 'soccer_uefa_europa_league', 'group': 'Soccer', 'title': 'UEFA Europa League', 'description': 'European Europa League', 'active': True, 'has_outrights': False}, {'key': 'soccer_uefa_european_championship', 'group': 'Soccer', 'title': 'UEFA Euro 2024', 'description': 'UEFA European Championship', 'active': True, 'has_outrights': False}, {'key': 'soccer_uefa_nations_league', 'group': 'Soccer', 'title': 'UEFA Nations League', 'description': 'UEFA Nations League', 'active': False, 'has_outrights': False}, {'key': 'soccer_usa_mls', 'group': 'Soccer', 'title': 'MLS', 'description': 'Major League Soccer', 'active': True, 'has_outrights': False}, {'key': 'tennis_atp_aus_open_singles', 'group': 'Tennis', 'title': 'ATP Australian Open', 'description': "Men's Singles", 'active': False, 'has_outrights': False}, {'key': 'tennis_atp_french_open', 'group': 'Tennis', 'title': 'ATP French Open', 'description': "Men's Singles", 'active': False, 'has_outrights': False}, {'key': 'tennis_atp_us_open', 'group': 'Tennis', 'title': 'ATP US Open', 'description': "Men's Singles", 'active': False, 'has_outrights': False}, {'key': 'tennis_atp_wimbledon', 'group': 'Tennis', 'title': 'ATP Wimbledon', 'description': "Men's Singles", 'active': False, 'has_outrights': False}, {'key': 'tennis_wta_aus_open_singles', 'group': 'Tennis', 'title': 'WTA Australian Open', 'description': "Women's Singles", 'active': False, 'has_outrights': False}, {'key': 'tennis_wta_french_open', 'group': 'Tennis', 'title': 'WTA French Open', 'description': "Women's Singles", 'active': False, 'has_outrights': False}, {'key': 'tennis_wta_us_open', 'group': 'Tennis', 'title': 'WTA US Open', 'description': "Women's Singles", 'active': False, 'has_outrights': False}, {'key': 'tennis_wta_wimbledon', 'group': 'Tennis', 'title': 'WTA Wimbledon', 'description': "Women's Singles", 'active': False, 'has_outrights': False}]
Remaining requests 500
Used requests 0

In [70]:
odds_response = r.get(
    f'https://api.the-odds-api.com/v4/sports/{sport}/odds',
    params={
        'api_key': odds_api_key,
        'regions': regions,
        'markets': markets,
        'oddsFormat': odds_format,
        'dateFormat': date_format,
    }
)

if odds_response.status_code != 200:
    print(f'Failed to get sports: status_code {odds_response.status_code}, response body {odds_response.text}')

else:
    #dump the list of dictionaries provided by json output via api call in to a python data structure for further parsing
    odds_data = odds_response.json()


    
    

    # Check the usage quota
    print('Remaining requests', odds_response.headers['x-requests-remaining'])
    print('Used requests', odds_response.headers['x-requests-used'])

Remaining requests 498
Used requests 2

In [5]:
rows_list = []
for i in odds_data:

    event_id = i['id']
    sport = i['sport_title']
    match_time = i['commence_time']
    home_team = i['home_team']
    away_team = i['away_team']

    for bookmakers in i['bookmakers']:

        bookmaker = bookmakers['title']
        bookmaker_last_update = bookmakers['last_update']

        for markets in bookmakers['markets']:
            
            market_event = markets['key']
            market_event_last_update = markets['last_update']

            for outcomes in markets['outcomes']:

                dictionary = {

                       'event_id': event_id,
                       'sport':sport,
                       'match_time':match_time,
                       'home_team':home_team,
                       'away_team':away_team,
                       'bookmaker':bookmaker,
                       'bookmaker_updated':bookmaker_last_update,
                       'market_event':market_event,
                       'market_event_update':market_event_last_update,
                       'outcome_name':outcomes['name'],
                       'price':outcomes['price'],
                       'points':outcomes.get('point')
                       

                      }
                
                rows_list.append(dictionary)

                
#df_full = pd.concat([pd.DataFrame([row]) for row in rows_list], ignore_index=True)
pd.DataFrame(rows_list).head(30)
        

#df_full.head()
    

bookmaker_actual = pd.DataFrame(rows_list)

bookmaker_actual.to_csv('bookmakers_actual.csv',index=True)

In [19]:
pivotted_odds = pd.pivot_table(bookmaker_actual,values = ['price','points'],index= ['event_id','market_event','outcome_name'],aggfunc=['mean','min','max']).reset_index()
pivotted_odds.columns = ['_'.join(col) for col in pivotted_odds.columns]
pivotted_odds.columns = [col[0:len(col)-1] if col[-1] == '_' else col for col in pivotted_odds.columns]
pivotted_odds.to_csv('pivotted_odds.csv',index=True)

pivotted_odds_and_bookmakers = pd.merge(bookmaker_actual,pivotted_odds,how='left',on=['event_id','market_event','outcome_name'])
pivotted_odds_and_bookmakers

,event_id,sport,match_time,home_team,away_team,bookmaker,bookmaker_updated,market_event,market_event_update,outcome_name,price,points,mean_points,mean_price,min_points,min_price,max_points,max_price
0,9aac4fc2c2231d9a8eab2a40c2a8cddf,MLB,2024-03-30T00:11:09Z,Houston Astros,New York Yankees,DraftKings,2024-03-30T03:03:35Z,h2h,2024-03-30T03:03:35Z,Houston Astros,3500,NaN,NaN,2940.000000,NaN,1900,NaN,4300
1,9aac4fc2c2231d9a8eab2a40c2a8cddf,MLB,2024-03-30T00:11:09Z,Houston Astros,New York Yankees,DraftKings,2024-03-30T03:03:35Z,h2h,2024-03-30T03:03:35Z,New York Yankees,-50000,NaN,NaN,-35600.000000,NaN,-100000,NaN,-8000
2,9aac4fc2c2231d9a8eab2a40c2a8cddf,MLB,2024-03-30T00:11:09Z,Houston Astros,New York Yankees,DraftKings,2024-03-30T03:03:35Z,spreads,2024-03-30T03:03:35Z,Houston Astros,154,4.5,4.944444,7.777778,4.5,-260,5.5,200
3,9aac4fc2c2231d9a8eab2a40c2a8cddf,MLB,2024-03-30T00:11:09Z,Houston Astros,New York Yankees,DraftKings,2024-03-30T03:03:35Z,spreads,2024-03-30T03:03:35Z,New York Yankees,-200,-4.5,-4.944444,-101.777778,-5.5,-260,-4.5,190
4,9aac4fc2c2231d9a8eab2a40c2a8cddf,MLB,2024-03-30T00:11:09Z,Houston Astros,New York Yankees,MyBookie.ag,2024-03-30T03:03:35Z,spreads,2024-03-30T03:03:35Z,Houston Astros,-225,5.5,4.944444,7.777778,4.5,-260,5.5,200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
977,48f6a5704c93970245f3f0c01292cda2,MLB,2024-03-31T01:40:00Z,Seattle Mariners,Boston Red Sox,PointsBet (US),2024-03-30T03:03:35Z,spreads,2024-03-30T03:03:35Z,Seattle Mariners,140,-1.5,-1.458333,122.583333,-1.5,-104,-1.0,148
978,48f6a5704c93970245f3f0c01292cda2,MLB,2024-03-31T01:40:00Z,Seattle Mariners,Boston Red Sox,BetUS,2024-03-30T03:03:35Z,h2h,2024-03-30T03:03:35Z,Boston Red Sox,130,NaN,NaN,129.642857,NaN,120,NaN,133
979,48f6a5704c93970245f3f0c01292cda2,MLB,2024-03-31T01:40:00Z,Seattle Mariners,Boston Red Sox,BetUS,2024-03-30T03:03:35Z,h2h,2024-03-30T03:03:35Z,Seattle Mariners,-145,NaN,NaN,-149.642857,NaN,-157,NaN,-144
980,48f6a5704c93970245f3f0c01292cda2,MLB,2024-03-31T01:40:00Z,Seattle Mariners,Boston Red Sox,BetUS,2024-03-30T03:03:35Z,spreads,2024-03-30T03:03:35Z,Boston Red Sox,-165,1.5,1.458333,-165.833333,1.0,-180,1.5,-118
981,48f6a5704c93970245f3f0c01292cda2,MLB,2024-03-31T01:40:00Z,Seattle Mariners,Boston Red Sox,BetUS,2024-03-30T03:03:35Z,spreads,2024-03-30T03:03:35Z,Seattle Mariners,145,-1.5,-1.458333,122.583333,-1.5,-104,-1.0,148

In [857]:
mlb_api_key = 'FWGQoAvCrTayY6TUyndhH1VD5bcNfrXu8ht7U4e1'
format = 'json'
language_code = 'en'
access_level = 'trial'
season_type = 'REG'



baseball_teams_response = r.get(
    f'https://api.sportradar.com/mlb/v7/en/league/teams.json?',
    params={
        'api_key': mlb_api_key,
        'access_level': access_level
      
    }
)

if baseball_teams_response.status_code != 200:
    print(f'Failed to get sports: status_code {baseball_teams_response.status_code}, response body {baseball_teams_response.text}')

else:
    #dump the list of dictionaries provided by json output via api call in to a python data structure for further parsing
    baseball_teams_data = baseball_teams_response.json()

league_name = baseball_teams_data['league']['alias']

In [858]:
mlb_teams = []
for i in baseball_teams_data['teams']:
    team_name = i.get('name')
    market_name = i.get('market','No Market')
    team_id = i.get('id')

    dictionary = {

        'league_name':league_name,
        'team_name':team_name,
        'market_name':market_name,
        'team_id':team_id
    }

    mlb_teams.append(dictionary)

baseball_teams = pd.DataFrame(mlb_teams)

baseball_teams = baseball_teams[baseball_teams.market_name != 'No Market']

In [907]:

team_id = '44671792-dc02-4fdd-a5ad-f5f17edaa9d7'
season_year = '2023'

baseball_seasonal_stats = r.get(
    f'https://api.sportradar.com/mlb/{access_level}/v7/{language_code}/seasons/{season_year}/{season_type}/teams/{team_id}/statistics.{format}',

    params = {

        'api_key':mlb_api_key,
        'language_code':language_code,
        'access_level':access_level,
        'year':season_year,
        'team_id':team_id,
        'season_type':season_type,
        'format':format
        }
    
    
)

if baseball_seasonal_stats.status_code != 200:
    print(f'Failed to get sports: status_code {baseball_seasonal_stats.status_code}, response body {baseball_seasonal_stats.text}')

else:
    #dump the list of dictionaries provided by json output via api call in to a python data structure for further parsing
    baseball_seasonal_stats = baseball_seasonal_stats.json()

In [908]:
team_name = baseball_seasonal_stats.get('name','No Team Name')
team_market = baseball_seasonal_stats.get('market','No Market')
team_id = baseball_seasonal_stats.get('id','No Team ID')
team_season_id = baseball_seasonal_stats['season'].get('id','No Season ID')
team_year = baseball_seasonal_stats['season'].get('year','0001')
team_stats_category = []
for label, stats in baseball_seasonal_stats['statistics'].items():

    stat_category = label

    for key, value in stats.items():

        stat_sub_category = key

        for i in value:
            
            statistic_parent_name = i
            
            if type(value[i]) != dict:
                dictionary = {
                              'team_id':team_id,
                              'season_id':team_season_id,
                              'stat_category':label,
                              'stat_sub_category':key,
                              'statistical_parent_name':statistic_parent_name,
                               'value':value[i]
                                  }
                team_stats_category.append(dictionary)
            
        
            elif type(value[i]) == dict:
                
                for j in value[i]:
                    
                    dictionary = {
                                  'team_id':team_id,
                                  'season_id':team_season_id,
                                  'stat_category':label,
                                  'stat_sub_category':key,
                                  'statistical_parent_name':statistic_parent_name,
                                   j:value[i].get(j,0)
                                  }
                    team_stats_category.append(dictionary) 
            


team_df = pd.DataFrame(team_stats_category)
#pivotted_team_df = pd.pivot_table(team_df,index = ['team_id','season_id','stat_category','stat_sub_category','statistical_parent_name'],aggfunc='sum').reset_index()


team_df_fielding = team_df[team_df['stat_category'] == 'fielding'].reset_index(drop=True)
team_df_hitting = team_df[team_df['stat_category'] == 'hitting'].reset_index(drop=True)
team_df_pitching = team_df[team_df['stat_category'] == 'pitching'].reset_index(drop=True)


team_df_fielding.dropna(axis = 1, how = 'all',inplace=True)

team_df_hitting.dropna(axis = 1, how = 'all',inplace=True)

team_df_pitching.dropna(axis = 1, how = 'all',inplace=True)

#team_df.to_csv('team_stats.csv', index=True)
#team_df_fielding.to_csv('fielding.csv',index=True)
#team_df_hitting.to_csv('hitting.csv',index=True)
#team_df_pitching.to_csv('pitching.csv',index=True)

In [909]:

def get_max_array_values_for_stats(df, ls, ls1):

   value_location = df.columns.get_loc('value')
   columns_to_float = df.columns[value_location:]
   df[columns_to_float] = df[columns_to_float].astype(float)
   
   for i in df.values:

      
      try:
         ls.append(np.nanmax(i[value_location:]))
         
      except TypeError:
         print(TypeError)
      

   for df_row_index, rows in df.iterrows():
      

      counter = 0

      for name, value in rows.items():
            
            if counter >= value_location and not pd.isna(value):
                #print(name,value)
                ls1.append(rows['statistical_parent_name']+'_'+name)
            else:
                pass
               
            counter += 1

   df.loc[:,'value'] = ls
   df.loc[:,'statistical_parent_name'] = ls1
   
   df = df.iloc[:,:value_location+1]
   

   
   return df

In [910]:
get_max_array_values_for_stats(df = team_df_fielding, ls = [],ls1 = [])
get_max_array_values_for_stats(df = team_df_hitting, ls = [],ls1 = [])
get_max_array_values_for_stats(df = team_df_pitching, ls = [],ls1 = [])

,team_id,season_id,stat_category,stat_sub_category,statistical_parent_name,value
0,44671792-dc02-4fdd-a5ad-f5f17edaa9d7,c8bca8f4-fb0f-44ed-95e0-8ced816ae8d8,pitching,overall,oba_value,0.2760
1,44671792-dc02-4fdd-a5ad-f5f17edaa9d7,c8bca8f4-fb0f-44ed-95e0-8ced816ae8d8,pitching,overall,lob_value,2462.0000
2,44671792-dc02-4fdd-a5ad-f5f17edaa9d7,c8bca8f4-fb0f-44ed-95e0-8ced816ae8d8,pitching,overall,era_value,4.7890
3,44671792-dc02-4fdd-a5ad-f5f17edaa9d7,c8bca8f4-fb0f-44ed-95e0-8ced816ae8d8,pitching,overall,k9_value,7.6590
4,44671792-dc02-4fdd-a5ad-f5f17edaa9d7,c8bca8f4-fb0f-44ed-95e0-8ced816ae8d8,pitching,overall,whip_value,1.4555
...,...,...,...,...,...,...
239,44671792-dc02-4fdd-a5ad-f5f17edaa9d7,c8bca8f4-fb0f-44ed-95e0-8ced816ae8d8,pitching,bullpen,games_win,28.0000
240,44671792-dc02-4fdd-a5ad-f5f17edaa9d7,c8bca8f4-fb0f-44ed-95e0-8ced816ae8d8,pitching,bullpen,games_loss,27.0000
241,44671792-dc02-4fdd-a5ad-f5f17edaa9d7,c8bca8f4-fb0f-44ed-95e0-8ced816ae8d8,pitching,bullpen,games_save,36.0000
242,44671792-dc02-4fdd-a5ad-f5f17edaa9d7,c8bca8f4-fb0f-44ed-95e0-8ced816ae8d8,pitching,bullpen,games_hold,89.0000
243,44671792-dc02-4fdd-a5ad-f5f17edaa9d7,c8bca8f4-fb0f-44ed-95e0-8ced816ae8d8,pitching,bullpen,games_blown_save,28.0000

In [911]:
team_df_fielding_pivotted = pd.pivot_table(team_df_fielding,index=['team_id','season_id','stat_category','stat_sub_category'],columns=['statistical_parent_name'],values = 'value',aggfunc='sum')
team_df_hitting_pivotted = pd.pivot_table(team_df_hitting,index = ['team_id','season_id','stat_category','stat_sub_category'], columns = ['statistical_parent_name'], values = 'value',aggfunc = 'sum')
team_df_pitching_pivotted = pd.pivot_table(team_df_pitching,index = ['team_id','season_id','stat_category','stat_sub_category'],columns = ['statistical_parent_name'],values = 'value',aggfunc = 'sum')

In [947]:
players = []
player_stats = []
player_sub_category_stats_list = []

for i in baseball_seasonal_stats['players']:
    
    preferred_name = i['preferred_name']
    first_name = i['first_name']
    last_name = i['last_name']
    player_id = i['id']
    position = i['position']
    primary_position = i['primary_position']

    dictionary = {
                  'id':player_id,
                  'player_first_name':first_name,
                  'player_last_name':last_name,
                  'position':position,
                  'primary_position':primary_position

                 }
    
    players.append(dictionary)

    for label, stats in i['statistics'].items():
        
        
        stat_category = label

        for key, value in stats.items():
            stat_sub_category = key
            if type(value) == list:
                pass
            else:
                for sub_key, sub_value in value.items():
                    if type(sub_value) == dict:
                       player_specific_stat_category = sub_key
                       for k, v in sub_value.items():
                          
                           dictionary_1 = {
                                         'player_id':player_id,
                                         'stat_category':stat_category,
                                         'stat_sub_category':stat_sub_category,
                                         'player_specific_stat_category':player_specific_stat_category,
                                         'player_specific_stat_category_name':k,
                                         'player_specific_stat_category_name_value':v

                               
                                        }
                           player_sub_category_stats_list.append(dictionary_1)
                    else:
                            dictionary_2 = {
                                            'player_id':player_id,
                                            'stat_category':stat_category,
                                            'stat_sub_category':stat_sub_category,
                                            'player_specific_stat_category':player_specific_stat_category,
                                            'player_specific_stat_category':sub_key,
                                            'player_specific_stat_category_value':sub_value

                                           }
                            
                            player_stats.append(dictionary_2)

[{'id': 'ecee463a-f7fb-43ad-9a71-d20c3e4c5d38',
  'player_first_name': 'Joseph',
  'player_last_name': 'Romero',
  'position': 'P',
  'primary_position': 'RP'},
 {'id': '6162380d-5201-4e3c-a1a3-0d3db5afc356',
  'player_first_name': 'Masyn',
  'player_last_name': 'Winn',
  'position': 'IF',
  'primary_position': 'SS'},
 {'id': '8babdbd4-d607-4bb0-a6c1-708c247c08ed',
  'player_first_name': 'Brendan',
  'player_last_name': 'Donovan',
  'position': 'OF',
  'primary_position': 'LF'},
 {'id': '65fc46ca-350d-4eaf-bc40-8851c3378bc6',
  'player_first_name': 'Tyler',
  'player_last_name': "O'Neill",
  'position': 'OF',
  'primary_position': 'RF'},
 {'id': 'cf302aef-cb3a-4626-ba44-a9bc7bbb3f5b',
  'player_first_name': 'Paul',
  'player_last_name': 'DeJong',
  'position': 'IF',
  'primary_position': 'SS'},
 {'id': 'f3719f44-d0f6-4d30-9bb3-22a3f315aae7',
  'player_first_name': 'Génesis',
  'player_last_name': 'Cabrera',
  'position': 'P',
  'primary_position': 'RP'},
 {'id': '96f75024-d2cb-4c0e-a887-82fd1455c1bb',
  'player_first_name': 'Felipe',
  'player_last_name': 'Barrera',
  'position': 'C',
  'primary_position': 'C'},
 {'id': '425cd8ba-6803-4970-972d-033ce47fa53a',
  'player_first_name': 'Iván',
  'player_last_name': 'Herrera',
  'position': 'C',
  'primary_position': 'C'},
 {'id': '24887442-7de5-4d3d-ab41-3a95e68828ec',
  'player_first_name': 'Richard',
  'player_last_name': 'Palacios',
  'position': 'OF',
  'primary_position': 'RF'},
 {'id': '4d6e9c2b-c7da-41ee-bb9d-f5e3f1a72730',
  'player_first_name': 'Irving',
  'player_last_name': 'Lopez',
  'position': 'IF',
  'primary_position': '2B'},
 {'id': '512c35f8-0ed7-448b-a654-ad28842d9263',
  'player_first_name': 'Juniel',
  'player_last_name': 'Querecuto',
  'position': 'IF',
  'primary_position': '3B'},
 {'id': '626336dd-9bdc-43da-9bcc-bcd412530bd3',
  'player_first_name': 'Andrew',
  'player_last_name': 'Knizner',
  'position': 'C',
  'primary_position': 'C'},
 {'id': '57136a41-44d2-4b33-b942-f45b0015870d',
  'player_first_name': 'Óscar',
  'player_last_name': 'Mercado',
  'position': 'OF',
  'primary_position': 'RF'},
 {'id': '3aea48c2-9d7c-46bc-b48e-627cbfa2a954',
  'player_first_name': 'Thomas',
  'player_last_name': 'Edman',
  'position': 'IF',
  'primary_position': 'SS'},
 {'id': 'fd0239d3-7703-4dfa-a54c-9c0c7a1baf2f',
  'player_first_name': 'Luken',
  'player_last_name': 'Baker',
  'position': 'IF',
  'primary_position': '1B'},
 {'id': 'aec77ff1-c238-449c-9af6-ed76ff9dd702',
  'player_first_name': 'Nolan',
  'player_last_name': 'Arenado',
  'position': 'IF',
  'primary_position': '3B'},
 {'id': '862615a7-5f5f-45f7-bb55-d774f97da6a2',
  'player_first_name': 'Nolan',
  'player_last_name': 'Gorman',
  'position': 'IF',
  'primary_position': '2B'},
 {'id': '99518b96-7d38-4f19-8c49-cafbac98ea74',
  'player_first_name': 'Lars',
  'player_last_name': 'Nootbaar',
  'position': 'OF',
  'primary_position': 'LF'},
 {'id': '7941825b-0909-40e8-b680-8c6493f24c89',
  'player_first_name': 'Jordan',
  'player_last_name': 'Walker',
  'position': 'OF',
  'primary_position': 'RF'},
 {'id': '4695cab6-a42f-4ea2-b8dc-f2d2de70206c',
  'player_first_name': 'Michael',
  'player_last_name': 'Siani',
  'position': 'OF',
  'primary_position': 'CF'},
 {'id': 'a1fe37fa-3159-4696-9ebc-0cd832d4e8f5',
  'player_first_name': 'Juan',
  'player_last_name': 'Yepez',
  'position': 'OF',
  'primary_position': 'LF'},
 {'id': '991ace91-d77f-4fad-b7a8-e94090299949',
  'player_first_name': 'Alec',
  'player_last_name': 'Burleson',
  'position': 'OF',
  'primary_position': 'RF'},
 {'id': '7b6abb04-541e-4d96-b0d5-2cf6e4bc4695',
  'player_first_name': 'Ryan',
  'player_last_name': 'Helsley',
  'position': 'P',
  'primary_position': 'RP'},
 {'id': '3a2d8084-65b5-4579-9eb6-adfcffa0fcd2',
  'player_first_name': 'José',
  'player_last_name': 'Fermín',
  'position': 'IF',
  'primary_position': '2B'},
 {'id': 'd585374f-09b3-4a95-97c8-756650458f0d',
  'player_first_name': 'Taylor',
  'player_last_name': 'Motter',
  'position': 'IF',
  'primary_position': '2B'},
 {'id': '9d93f121-f032-407d-bb30-ad3593641db9',
  'player_first_name': 'Willson',
  'player_last_name': 'Contreras',
  'position': 'C',
  'primary_position': 'C'},
 {'id': 'efd55e67-319e-4e76-b850-5f5ad00ce941',
  'player_first_name': 'James',
  'player_last_name': 'Naile',
  'position': 'P',
  'primary_position': 'RP'},
 {'id': '0ebf2165-048e-4392-b057-2e57d6b6b95e',
  'player_first_name': 'Dylan',
  'player_last_name': 'Carlson',
  'position': 'OF',
  'primary_position': 'CF'},
 {'id': 'c399c961-1b45-430c-858e-f0a33ae0af85',
  'player_first_name': 'Adam',
  'player_last_name': 'Wainwright',
  'position': 'P',
  'primary_position': 'SP'},
 {'id': '7c9c97fd-7a89-49e1-830b-0274a5c2209a',
  'player_first_name': 'Paul',
  'player_last_name': 'Goldschmidt',
  'position': 'IF',
  'primary_position': '1B'},
 {'id': 'c8f9ffa5-d070-4c45-b415-c6331e0f3f7a',
  'player_first_name': 'Zachary',
  'player_last_name': 'Thompson',
  'position': 'P',
  'primary_position': 'RP'},
 {'id': 'b6064f09-31ae-4d05-832c-2f4c4043c7cb',
  'player_first_name': 'Jordan',
  'player_last_name': 'Hicks',
  'position': 'P',
  'primary_position': 'SP'},
 {'id': '0f4978b2-11a8-42c4-af98-e7c8a9b42365',
  'player_first_name': 'Drew',
  'player_last_name': 'Rom',
  'position': 'P',
  'primary_position': 'SP'},
 {'id': '5522ef4b-d436-4738-94d6-78a2c1c5a3ae',
  'player_first_name': 'Matthew',
  'player_last_name': 'Liberatore',
  'position': 'P',
  'primary_position': 'SP'},
 {'id': '94006ace-427f-4b5a-bd5b-367118fd4eb2',
  'player_first_name': 'Drew',
  'player_last_name': 'VerHagen',
  'position': 'P',
  'primary_position': 'RP'},
 {'id': '262b24b7-ce98-4885-8715-2732a61db10d',
  'player_first_name': 'Miles',
  'player_last_name': 'Mikolas',
  'position': 'P',
  'primary_position': 'SP'},
 {'id': 'fd954c71-a360-41d8-846e-7faf831b6256',
  'player_first_name': 'Dakota',
  'player_last_name': 'Hudson',
  'position': 'P',
  'primary_position': 'SP'},
 {'id': '19970eff-23b1-4fde-96b2-a8dbc4e8c07a',
  'player_first_name': 'Dennis',
  'player_last_name': 'Tepera',
  'position': 'P',
  'primary_position': 'RP'},
 {'id': '8c51ad39-f1f6-4e63-9e0d-a8d99d195450',
  'player_first_name': 'Jacob',
  'player_last_name': 'Barnes',
  'position': 'P',
  'primary_position': 'RP'},
 {'id': '07b26fab-24c4-4a02-9995-36f9cb5352d8',
  'player_first_name': 'Giovanny',
  'player_last_name': 'Gallegos',
  'position': 'P',
  'primary_position': 'RP'},
 {'id': '66ca1e33-1303-4354-9f94-edae0d332456',
  'player_first_name': 'Kyle',
  'player_last_name': 'Leahy',
  'position': 'P',
  'primary_position': 'RP'},
 {'id': '051b28a4-a189-440e-bef0-3d922819e223',
  'player_first_name': 'Casey',
  'player_last_name': 'Lawrence',
  'position': 'P',
  'primary_position': 'RP'},
 {'id': '6740469d-ec38-4c8a-ae12-2530c0e5e395',
  'player_first_name': 'Guillermo',
  'player_last_name': 'Zuñiga',
  'position': 'P',
  'primary_position': 'RP'},
 {'id': 'e1ca8a23-8fd5-49bb-b125-9c695aa4e795',
  'player_first_name': 'Patrick',
  'player_last_name': 'Naughton',
  'position': 'P',
  'primary_position': 'RP'},
 {'id': '03fda22a-f8a3-45e8-80dc-bf8190a22020',
  'player_first_name': 'Steven',
  'player_last_name': 'Matz',
  'position': 'P',
  'primary_position': 'SP'},
 {'id': 'c6ed1126-55d9-496c-a23c-523d0029b6d7',
  'player_first_name': 'Andrew',
  'player_last_name': 'Suárez',
  'position': 'P',
  'primary_position': 'RP'},
 {'id': '6e8d6f60-4274-465b-b6f6-86fc916c7335',
  'player_first_name': 'Jacob',
  'player_last_name': 'Woodford',
  'position': 'P',
  'primary_position': 'SP'},
 {'id': '9263d36c-cca2-4359-854e-b4139a494008',
  'player_first_name': 'John',
  'player_last_name': 'King',
  'position': 'P',
  'primary_position': 'RP'},
 {'id': '6b4748c0-1b93-4a58-9896-80a04af32c5b',
  'player_first_name': 'Neil',
  'player_last_name': 'Pallante',
  'position': 'P',
  'primary_position': 'RP'},
 {'id': '9c506364-e0fa-45b9-9313-16f6e87e0327',
  'player_first_name': 'Jack',
  'player_last_name': 'Flaherty',
  'position': 'P',
  'primary_position': 'SP'},
 {'id': 'e96d88f5-3593-48fb-b1fd-840b41c08cc5',
  'player_first_name': 'Jordan',
  'player_last_name': 'Montgomery',
  'position': 'P',
  'primary_position': 'SP'},
 {'id': 'cdd52cf2-b10d-456a-9a92-1d74e1f05bac',
  'player_first_name': 'Christopher',
  'player_last_name': 'Stratton',
  'position': 'P',
  'primary_position': 'RP'}]